# Generated by Django 4.1.12 on 2023-10-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ramo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_ramo', models.CharField(max_length=7)),
            ],
        ),
        migrations.DeleteModel(
            name='ramos',
        ),
    ]
