# Generated by Django 4.1.12 on 2023-10-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letoapp', '0002_ramo_delete_ramos'),
    ]

    operations = [
        migrations.CreateModel(
            name='horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('_horario', models.CharField(max_length=100)),
            ],
        ),
    ]
