# Generated by Django 4.1.12 on 2023-10-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letoapp', '0003_horario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horario',
            old_name='_horario',
            new_name='n_horario',
        ),
        migrations.AddField(
            model_name='horario',
            name='rol',
            field=models.CharField(default=123456789, max_length=11),
            preserve_default=False,
        ),
    ]
