# Generated by Django 4.1.12 on 2023-10-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letoapp', '0004_rename__horario_horario_n_horario_horario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='estudiar',
            field=models.CharField(default='0', max_length=7),
        ),
    ]
