# Generated by Django 4.1.12 on 2023-10-31 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letoapp', '0005_horario_estudiar'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('rol', models.CharField(max_length=11)),
                ('n_horario', models.CharField(max_length=100)),
                ('estudiar', models.CharField(default='0', max_length=7)),
            ],
        ),
    ]
